name: CI

on:
  push:
    branches: [main, master]
    paths:
      - 'src/services/**'
      - 'src/app/api/**'
      - 'tests/**'
      - 'scripts/**'
      - 'package.json'
      - 'tsconfig.json'
      - '.github/workflows/ci.yml'
  pull_request:
    branches: [main, master]
    paths:
      - 'src/services/**'
      - 'src/app/api/**'
      - 'tests/**'
      - 'scripts/**'
      - 'package.json'
      - 'tsconfig.json'
      - '.github/workflows/ci.yml'

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Install dependencies
        run: npm install
      - name: Lint
        run: npm run lint || echo 'Lint step skipped (add lint script to package.json)'
      - name: Test
        run: npm test
